# Generated by Django 5.1.2 on 2025-07-03 16:08

import django.db.models.deletion
import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                help_text="format: not required",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="inventory.category",
                verbose_name="parent of category",
            ),
        ),
    ]
